### ISSUE TITLE
Fail to use blessed ListItem content containing chinese characters as key of Map

### ISSUE THREAD

**Issue by chinggg** [wechaty/cli#2]
Now I am using `Map` to store contacts/rooms and messages.
```typescript
// name must be unique
let contactList: Array<Contact>
let friendList: Array<Contact>  // friend = individual contact
let roomList: Array<Room>
let friendByName: Map<string, Contact> = new Map()
let roomByName: Map<string, Room> = new Map()
let msgByName: Map<string, Array<Message>>  = new Map()
```
Since some puppet cannot provide constant id, I use "name" as key to identify different contacts/rooms. The "name" is defined by the `getKey()` function and it is the bridge between message and its source(room | contact) .
```typescript
async function getKey(s: Contact | Room) {
  if (s instanceof Contact) {
    return await s.alias() || s.name() || s.id
  } else {
    return await s.topic() || s.id
  }
}
```

Once the bot is ready, it will get all friend and room then display their names as items of the leftPanel. There should be one-to-one correspondences between `friendByName.keys()`+`roomByName.keys()` and items of leftPanel.
```typescript
// when login complete, get all friend and room info and display on the leftPanel
async function onReady(logElement: contrib.Widgets.LogElement) {
    bot.say('Wechaty ready!').catch(console.error)
 
    contactList = await bot.Contact.findAll()
    friendList = contactList.filter(x => x.type() !== Contact.Type.Official)
    await Promise.all(friendList.map(async f => friendByName.set(await getKey(f), f)));
    [...friendByName.keys()].forEach(f => leftPanel.add(f))
    msgConsole.log(`Totally ${friendList.length} friends`)
    msgConsole.log(friendByName.size.toString())
 
    roomList = await bot.Room.findAll()
    await Promise.all(roomList.map(async f => roomByName.set(await getKey(f), f)));
    [...roomByName.keys()].forEach(r => leftPanel.add(r))
    msgConsole.log(`Totally ${roomList.length} rooms`);
    msgConsole.log(roomByName.size.toString())
    screen.render()
}
```
In the `onMessage` function, I get the source of message then store the message in the `msgByName` map.
```typescript
// when login complete, get all friend/room info then display on the leftPanel
async function onMessage(message: Message, logElement: contrib.Widgets.LogElement) {
  const type = message.type()
  logElement.log(message.toString())
  const source = message.room() || message.talker()
  const k = await getKey(source)
  if (!msgByName.has(k)) msgByName.set(k,[])
  msgByName.get(k)!.push(message)
  if (type != Message.Type.Text) {
      // ... not important
  }
  screen.render()
}
```
When user clicks a item of leftPanel, the callback function of `select item` event should take effect to display messages from corresponding source.
But I find it will always fail to get corresponding source if and only if the name of source contains chinese character, and even succeed for other non-alphanumeric chracters like 拼音.
Since `ListElement` of blessed does not provide a way to get on specific item or iterate all its items, I test one specific contact with name `李涵` and directly compare the string with the content of selected item of `李涵`. It turns out they are not the same, which means **if the content of blessed element containing chinese character, it may have been changed to be different from the raw text though they are displayed the same.** This is the only explanation I can think of.

```typescript
leftPanel.on('select item', async (item, index) => {
  const name = item.getContent().trim()
  msgConsole.setContent('')
  rightPanel.setContent('')
  const msgs = msgByName.get(name) || ['No message!']
  msgs.forEach(m => msgConsole.add(m.toString()))
  const source: Contact | Room | undefined = friendByName.get(name) || roomByName.get(name)
  msgConsole.log(name)
  msgConsole.log(friendByName.has(name).toString())
  msgConsole.log(roomByName.has(name).toString())
  if(source === undefined) {  // 所有中文字符都失败
    msgConsole.log('error: source no found')
    // click '李涵' to test a specified name
    msgConsole.log('李涵')
    msgConsole.log((name == '李涵').toString())  // false! although they are displayed the same
    msgConsole.log(friendByName.has('李涵').toString())  // true, as expected
    Array.from(friendByName.keys()).forEach(s => msgConsole.log(s))
  } else {
    msgConsole.log(await getKey(source))
  }
  if (source instanceof Room) {
    // ... not important
  }
})
```

I have been diving into the source code (specifically `element.js` and `list.js`) of blessed to understand what happens between `add()` and `getContent()` of `ListElement` but I have achieved little so far. 
@huan Can you have a look at https://github.com/chinggg/wechaty-cli/blob/error-chinese-content/index.ts to see if I have made any mistakes or blessed does make some changes to the real content at spare? If it is the latter, is there any way better to store and display messages by source? Thanks!

**Comment by huan** [comment]
Thanks for asking the question with a detailed explanation and the source code references.

**My option would be using the `id` as the key of your `Map`, instead of using "name".**

The Wechaty CLI reload everything when a user starts it, and the most important user interface of the CLI is to let the user use this application to chat (or debug). 

So I believe we can safely ignore the "some puppet cannot provide constant id" problem because it will not affect our system.

Please let me know if using the `id` can solve your problem or not.

**Comment by chinggg** [comment]
> Thanks for asking the question with a detailed explanation and the source code references.
> 
> **My option would be using the `id` as the key of your `Map`, instead of using "name".**
> 
> The Wechaty CLI reload everything when a user starts it, and the most important user interface of the CLI is to let the user use this application to chat (or debug).
> 
> So I believe we can safely ignore the "some puppet cannot provide constant id" problem because it will not affect our system.
> 
> Please let me know if using the `id` can solve your problem or not.

@huan 
I did not use `id` because `ListElement` of blessed seems not to be so DIY-friendly. IMO, it is content-oriented instead of object-oriented.
```typescript
List.prototype.add =
List.prototype.addItem =
List.prototype.appendItem = function(content) {
  content = typeof content === 'string' ? content : content.getContent();

  var item = this.createItem(content);
  // ...
}

List.prototype.setItem = function(child, content) {
  content = typeof content === 'string' ? content : content.getContent();
  var i = this.getItemIndex(child);
  if (!~i) return;
  this.items[i].setContent(content);
  this.ritems[i] = content;
};

List.prototype.setItems = function(items) {
  var original = this.items.slice()
    , selected = this.selected
    , sel = this.ritems[this.selected]
    , i = 0;

  items = items.slice();

  this.select(0);

  for (; i < items.length; i++) {
    if (this.items[i]) {
      this.items[i].setContent(items[i]);
    } else {
      this.add(items[i]);
    }
  }
  // ...
}
```

As we can see, `ListElement` methods `add()`, `setitem()`, `setItems()` accept BlessedElement as arguments but they care only about **content** by using `getContent()`. So even if we can create BlessedElements with extra hidden info about `id`, `leftPanel` will only have string as content.

The only things we can get from the `select` callback are item(it will not contain extra info other than text content) and index. If I cannot fix the chinese character issue, maybe we have to depend on `index` as the key though it may be difficult to maintain if we expect new message source to be placed on the top.

FYI, the source code dealing with content is in `element.js`. 
```typescript
Element.prototype.setContent = function(content, noClear, noTags) {
  if (!noClear) this.clearPos();
  this.content = content || '';
  this.parseContent(noTags);
  this.emit('set content');
};

Element.prototype.getContent = function() {
  if (!this._clines) return '';
  return this._clines.fake.join('\n');
};
```
To sum up, the problem is "you can only get what your see" but "WYS is not WYG" for chinese character. 
I have made small test like below to prove the issue with chinese characters.
```typescript
export const screenOption = {
  smartCSR: true,
  useBCE: true,
  autoPadding: true,
  dockBorders: true,
  forceUnicode: true,
  fullUnicode: true,
  sendFocus: true,
  warnings: true
}
const screen = blessed.screen(screenOption)
screen.title = 'test'
const logElement = blessed.log(scrollOption)
const list = blessed.list({
  parent: screen,
  ...scrollOption,
  style: listStyle,
  label: 'list'
})

list.add('一')
list.add('two')

list.on('select item', (item, index) => {
  const text = item.getContent()
  const ans1 = (text == '一').toString()
  const ans2 = (text == 'two').toString()
  list.add(ans1)
  list.add(ans2)
})
```
The result is always false if I clicked chinese character, which proves my assumption.
Sadly, [blessed](https://github.com/chjj/blessed) has no update since 2016.

**Comment by huan** [comment]
I understand that the ListElement can not fulfill your requirement.

Have you tried the TreeElement? If I remember right, the tree items can hold more information for us, for example, the file path.

![image](https://user-images.githubusercontent.com/1361891/127590519-51c4f8fe-6a24-491d-92a7-6b5c49df4fcd.png)

You can refer the source code at <https://github.com/huan/node-facenet/blob/55f892b277e26656ffcda8bfc950a3e098feca6b/src/manager/alignment-embedding/alignment-embedding.ts#L41-L45>

**Comment by chinggg** [comment]
@huan Thanks! I almost forgot about TreeElemet, assuming it is only suitable for hierachical data like filesystem. After testing for quite a while, I found it can store extra data in its children. But the app always crashes when I try to interact with the leftPanel.

We can discuss it in #9, then make PR from `list2tree` branch to close both the two issues if it succeed. I will let you know if I need extra help.

**Comment by huan** [comment]
You are welcome, and good to know that you found a way to solve the problem!
