### ISSUE TITLE
Prepare to publish to NPM as name `wechaty-cli`

### ISSUE THREAD

**Issue by huan** [wechaty/cli#5]
Let's finish the NPM publishing before the mid-term.

You first need an npm account, then we can get this done in our next meeting.

**Comment by huan** [comment]
Have you registered the npm account?

Let's be ready to publish the cli to NPM as `wechaty-cli` in the next week.

**Comment by chinggg** [comment]
> Have you registered the npm account?
> 
> Let's be ready to publish the cli to NPM as `wechaty-cli` in the next week.

I have registered my npm account. Do I need to wait for meeting in the next week to publish to NPM?

**Comment by huan** [comment]
No you needn't. Please feel free to publish it by yourself, and then:

1. Add my npm account as a maintainer on npmjs.com. (my account name is `zixia`)
1. Get your npm authorization token, and set it as a secret named NPM_TOKEN in the repo settings

Please let me know after you have finished the above take, and then we will be able to setup the CI/CD with GitHub Actions for DevOps.

**Comment by chinggg** [comment]
> No you needn't. Please feel free to publish it by yourself, and then:
> 
> 1. Add my npm account as a maintainer on npmjs.com. (my account name is `zixia`)
> 2. Get your npm authorization token, and set it as a secret named NPM_TOKEN in the repo settings
> 
> Please let me know after you have finished the above take, and then we will be able to setup the CI/CD with GitHub Actions for DevOps.

Finished. https://www.npmjs.com/package/wechaty-cli

**Comment by chinggg** [comment]
Oh I unpublished the npm package because I find some errors, but now I have to wait for 24 hours. see https://github.com/npm/cli/issues/958

**Comment by huan** [comment]
We have published at https://www.npmjs.com/package/wechaty-cli
