### ISSUE TITLE
Move this repo to the Wechaty org

### ISSUE THREAD

**Issue by huan** [wechaty/cli#6]
Please move this repo to github.com/wechaty/wechaty-cli so that we can get the nice osschat UrlLink for issue discussions, and the better team management with the org.

**Comment by chinggg** [comment]
Once #11 is merged, this repo can be moved to Wechaty org, but I am not sure which teams should have access. [Summer](https://github.com/orgs/wechaty/teams/summer) or [Commiters](https://github.com/orgs/wechaty/teams/commiters) or [Contributors](https://github.com/orgs/wechaty/teams/contributors) ?

**Comment by chinggg** [comment]
Once #11 is merged, this repo can be moved to Wechaty org, but I am not sure which teams should have access. Can I simply transfer this repo without selecting any teams?

**Comment by huan** [comment]
Yes, you can simply transfer this repo without selecting any teams. And we can add team access later.

**Comment by chinggg** [comment]
Done. Now I have no admin access to this repo.

**Comment by huan** [comment]
Great to have cli in our wechaty org now!

Admin privileges granted.
