### ISSUE TITLE
Use `TreeElement` as leftPanel to display contacts and rooms

### ISSUE THREAD

**Issue by chinggg** [wechaty/cli#9]
Since ListElement cannot meet our requirement as we discussed in #2, using TreeElement from  [blessed-contrib](https://github.com/yaronn/blessed-contrib#tree) may be better.

However, there are use cases where TreeElement is used to store complex object. In fact I can only find TreeElement to be used as file explorer (in [example](https://github.com/yaronn/blessed-contrib/blob/master/examples/explorer.js) and [node-facenet](https://github.com/huan/node-facenet/blob/master/src/manager/alignment-embedding/alignment-embedding.ts#L86-L151)).

After reading the doc and source code, I found TreeElement is able to store extra information. Although the [type declaration](https://github.com/yaronn/blessed-contrib/blob/master/index.d.ts#L413-L436) of TreeElement is incomplete, I can understand it better by trying to write the interface manually.
```typescript
// not completely correct
export interface TreeNode {
    name?: string,
    children?: TreeChildren | ((node: TreeNode) => TreeChildren | Promise<TreeChildren>),
    childrenContent?: TreeChildren,
    exteneded?: boolean,
    parent?: TreeNode,
    [custom: string]: any
}

export type TreeChildren = Record<TreeNode['name'], TreeNode>

export class TreeElement extends BoxElement implements IHasOptions<TreeOptions> {
    constructor(opts: TreeOptions)

    //...
    setData(data: TreeNode): void

    options: TreeOptions;
}
```
IMO, a node is an object that may have `name`, `children` and other properties. A root node is always needed to fulfill the TreeElement by `setData(root)` method. `children` of a node can be either object containing nodes or function returning that object. The latter may be prefered since it  is more flexible.

I expect to create leftPanel like below, but now when I try to extend friends, the app crash without visible info about the error.

- Friends (extended)
  - friend1
  - friend2
  - ...
- Rooms (exteneded)
  - room1
  - room2
  - ...

I write function below this to create an explorer(root node) for a bot. I can use `    Array.from(Object.values(await explorer.children(explorer))).forEach(s => msgConsole.log((s as any).real))` to print all the user ids, which means `childrenContent` has stored the extra information.
```typescript
function explore (bot: Wechaty) {
  return {
  name: 'Friends',
  real: bot.id,
  extended: true,
  children: async (self: any) => {
    if (self.childrenContent) {
      return self.childrenContent
    }
    const result = {} as any
    try {
      for (const friend of friends) {
        const name = await displayed(friend)
        result[name] = {name: name, real: friendByName.get(name)!.id, extended: false}
      }
    } catch(e) {
      console.log(e)
    }
    return result
  },
  } as contrib.Widgets.TreeNode
}
```

I will try to find the reason of crash, maybe it is related to [`children` as async function](https://github.com/yaronn/blessed-contrib/issues/44).

**Comment by chinggg** [comment]
I have changed children of root to be `friendRecord` instead of a function, which is more readable, but it still crash if I run `leftPanel.focus()` or simply click on leftPanel. It does throw error information on the screen but too transient to read and I cannot scroll back to see the top, so I cannot find which line cause the error.
Now the related code is like below:
```typescript
let friendRecord: contrib.Widgets.TreeChildren = {}
let friendRoot: contrib.Widgets.TreeNode = {
  name: 'Friends',
  extended: true
}

async function onReady(logElement: contrib.Widgets.LogElement) {
    bot.say('Wechaty ready!').catch(console.error)

    contacts = await bot.Contact.findAll()
    friends = contacts.filter(x => x.type() !== Contact.Type.Official).slice(0,5)
    for (const f of friends){
      const name = await displayed(f)
      nameByFriend.set(f, name)  // friendByName is not needed since we have friendRecord
      friendRecord[name!] = {
        name: name,
        extended: false
        // real: f
      }
    }
    // friendRoot.real = bot.userSelf()
    friendRoot.children = friendRecord
    leftPanel.setData(friendRoot)
    leftPanel.focus()  // this line will lead to crash
    // Array.from(Object.values(friendRoot.children as contrib.Widgets.TreeChildren)).forEach(x => msgConsole.log((x.real.id)))  // print all id
    //...
}
```
At first I assume the crash is caused by extra properties, so I leave only names. But it still crashes as before, even if I do nothing on select event.
![image](https://user-images.githubusercontent.com/24590067/127730311-0abf5945-3e52-4ae2-b217-54b29b89a9c1.png)

@huan Did you run into crashes when using TreeElement to develop `node-facenet`? If not, can you share your experience in debugging blessed-based app? It seems that error info always show on a temporary console then the app crash and quit, I can only see npm error log which is of no use.

**Comment by huan** [comment]
It's great to see that you have started using the tree element and it works!

For debugging: sorry it's too long ago, I can not remember anything. However, I believe the node-facenet manager is working without any problem, I hope you can find something from the source code over there.

BTW: I'd like to suggest that we can give high priority to #4 and #6, then we can get #5 done.

**Comment by chinggg** [comment]
> It's great to see that you have started using the tree element and it works!
> 
> For debugging: sorry it's too long ago, I can not remember anything. However, I believe the node-facenet manager is working without any problem, I hope you can find something from the source code over there.
> 
> BTW: I'd like to suggest that we can give high priority to #4 and #6, then we can get #5 done.

I have seen the two issues to prepare for publishing, but now the app lacks good design and code quality, will it be OK to merge current code to `main` branch and move it to `wechaty` org? I may feel a bit shameful to publish my low-quality code under wechaty org, but if you do not mind that, I can publish it first then make fixes and refactoring later 😹

**Comment by huan** [comment]
> will it be OK to merge the current code to the main branch and move it to wechaty org? 

It's ok for now, we can keep improving it by keeping working on it.

Please go ahead and plan for that, thank you very much.

**Comment by chinggg** [comment]
@huan Today some awesome developers have debugged the app for me patiently, the crash seems to be related to the implementation of `focus` and `render` within blessed library, which will cause `RangeError: Maximum call stack size exceeded`.
```
// infinite loop ...
at Tree.render (cli/node_modules/blessed-contrib/lib/widget/tree.js:152:52)
at cli/node_modules/blessed/lib/widgets/screen.js:738:8
at Array.forEach (<anonymous>)
at Screen.render (cli/node_modules/blessed/lib/widgets/screen.js:735:17)
at reposition (cli/node_modules/blessed/lib/widgets/element.js:968:17)
at Tree._labelScroll (cli/node_modules/blessed/lib/widgets/element.js:972:5)
at Tree._emit (cli/node_modules/blessed/lib/events.js:94:20)
at Tree.emit (cli/node_modules/blessed/lib/events.js:117:12)
at Tree.scroll (cli/node_modules/blessed/lib/widgets/scrollablebox.js:274:17)
at Tree.<anonymous> (cli/node_modules/blessed/lib/widgets/scrollablebox.js:222:8)
at Screen._focus (cli/node_modules/blessed/lib/widgets/screen.js:1680:10)
at Screen.focusPush (cli/node_modules/blessed/lib/widgets/screen.js:1620:8)
at Screen.focused (cli/node_modules/blessed/lib/widgets/screen.js:1697:15)
at List.focus (cli/node_modules/blessed/lib/widgets/element.js:329:30)
```
Related Issues: chjj/blessed#221

Good news! If I comment the line below in `Tree.prototype.render`, there will be no crash!
```typescript
if (this.screen.focused === this.rows) this.rows.focus();
```

**Comment by chinggg** [comment]
I debugged the app with vscode all day long. Eventually I found the reason why our app always crashes whenever `leftPanel`(TreeElement) is focused.

```typescript
Tree.prototype.focus = function() {
  this.rows.focus();   // this.rows: blessed.Widgets.ListElement
};

// if any element is focused
Element.prototype.focus = function() {
  return this.screen.focused = this;
};
```
The callback of `Screen.prototype.__defineSetter__('focused', el)` will then call `this.focusPush(el)`.
The last statement in `focusPush()` is `this._focus(el, old)`, where `old` is the tail of array `this.history`.

The trigger of infinite loop lies in function `Screen.prototype._focus()`:
```typescript
Screen.prototype._focus = function(self, old) {
  // Find a scrollable ancestor if we have one.
  var el = self;
  while (el = el.parent) {
    if (el.scrollable) break;
  }

  // If we're in a scrollable element,
  // automatically scroll to the focused element.
  if (el && !el.detached) {
    // NOTE: This is different from the other "visible" values - it needs the
    // visible height of the scrolling element itself, not the element within
    // it.
    var visible = self.screen.height - el.atop - el.itop - el.abottom - el.ibottom;
    if (self.rtop < el.childBase) {
      el.scrollTo(self.rtop);
      self.screen.render();
    } else if (self.rtop + self.height - self.ibottom > el.childBase + visible) {
      // Explanation for el.itop here: takes into account scrollable elements
      // with borders otherwise the element gets covered by the bottom border:
      el.scrollTo(self.rtop - (el.height - self.height) + el.itop, true);
      self.screen.render();
    }
  }
  // omitted
};
```
The initial value of `el` is still the ListElement inside TreeElement, and `el.parent` is the TreeElement.
I find the tree scrollable, so the while loop breaks with `el = TreeElement`, then `screen.render()` is likely to be called in the following if-statements.

`screen.render()` will make childrens of the screen to render, so the TreeElement will be rendered.
The if-statement in functioon `Tree.prototype.render()`, if evaluated true, will focus the ListElement again, which causes the infinite loop.
```typescript
Tree.prototype.render = function() {
  if (this.screen.focused === this.rows) this.rows.focus();

  this.rows.width = this.width - 3;
  this.rows.height = this.height - 3;
  Box.prototype.render.call(this);
};
```

**Comment by chinggg** [comment]
Now it seems to have no problem except that we cannot use scroll bar, but using arrow key and vim navigation keys like(j/k/g/G) is enough for now.

**Comment by chinggg** [comment]
contrib.tree has more bugs than I thought, most of which are related to `focus`:
- attempt to scroll tree will cause many focus events
- set style of focus on tree will also cause `stack size exceeded` https://github.com/yaronn/blessed-contrib/issues/197
